# Generated by Django 5.1.4 on 2024-12-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_contactus_blog_date_blog_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
