# Generated by Django 5.1.4 on 2024-12-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='first_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_photo/'),
        ),
        migrations.AddField(
            model_name='project',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_photo/'),
        ),
        migrations.AddField(
            model_name='project',
            name='third_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_photo/'),
        ),
    ]
