# Generated by Django 5.1.4 on 2024-12-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_project_first_image_project_second_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
