# Generated by Django 5.1.4 on 2024-12-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_contactus_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
